### ISSUE TITLE
Roadmap to Release MEI v5.0

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1162]
```mermaid
gantt
    dateFormat  YYYY-MM-DD
    title       Roadmap to MEI v5.0
    tickInterval 3month
    axisFormat %b %Y

    section Schema & Guidelines
    Release MEI v.4.0.1            :milestone,  ms1, 2019-04-12, 0d
    Back To ODD                     :milestone, ms2, 2020-11-10, 0d
    First Beta MEI Basic           : ms3, 2019-10-26,2023-08-31
    PDF Guidelines                  : ms4, 2023-05-23,2023-08-31
    Release MEI v5.0               :milestone, active, ms5, 2023-08-31, 0d

    section MECs
    2019 Wien                   :done, 2019-05-29, 4d
    2020 Boston/Online    :done, 2020-05-26, 4d
    2021 Alicante              :done, 2021-07-19, 4d
    2022 Halifax                :done, 2022-05-19, 4d
    2023 Paderborn          :active, 2023-09-04, 5d

    section Developer Workshops
    Nashville                 :done, 2019-10, 4d
    Online                     :done, 2020-11, 3d
    Berlin                      :done, 2022-10, 3d
    Charlottesville        :done, 2023-05, 5d
```

For the upcoming release, the follwing steps are needed:

### Before the release:

- [x] feature freeze on GH
- [x] Build workflow working
  - [x] #1125
  - [x] ~~#1166~~surpassed by #1187 
  - [x] reduce verbosity of terminal feedback #1200 
  - [x] #1202
- [x]  #1144  & #1163
- [x] release notes ready
- [x] comparison html ready
- [x] XSLT mei40To50 ready
- [x] #1256
- [x] relation of keysig issues #590 #727  #1010 in MEI 5.0 milestone and #1170 
- [x] https://github.com/music-encoding/sample-encodings/issues/81
- [x] create v4.0.1 encoding-tools release

### During the release:
  - [x] adjust version number to `v5.0`, see #1174
  - [x] #1250 
  - [x] add tag v5.0
  - [x] update GH action with release job
    - [x] only generate PDF for releases
  - [x] upgrade sample encodings https://github.com/music-encoding/sample-encodings/issues/76
  - [x] update examples in the guidelines: https://github.com/music-encoding/music-encoding/pull/1337
  - [x] add corresponding tags to sample encoding repo (guidelines and schema repo do not have tags)
  - [x] add release assets (Guidelines HTML & PDF , Schemata)
  - [x] add release notes
  - [x] include v5 guidelines in website menu: https://github.com/music-encoding/music-encoding.github.io/pull/501
  - [x] add v5 menu.html to `menus/v5/`: https://github.com/music-encoding/music-encoding.github.io/pull/503
  - [x] update schema & namespace section of the website
  - [x] update archive section of the website
  - [x] add comparison html to website

### After the release:
- [x] merge release to develop
- [x] push release assets to Zenodo
- [x] update version number to `v6.0-dev`
- [x] advertise release

-----
Future potential improvements copied over from #959 

POTENTIAL ANT IMPROVEMENTS

- [ ] #1203 
- [ ] https://github.com/bwbohl/music-encoding/tree/feature-build-on-pr
- [x] https://github.com/bwbohl/music-encoding/tree/feature_cleanBeforBuild

POTENTIAL STYLING IMPROVEMENTS

- [ ] #1204 
- [x] #1168

POTENTIAL OTHER IMPROVEMENTS

- [x] https://github.com/music-encoding/music-encoding/pull/806

**Comment by rettinghaus** [comment]
Can this be closed now?

**Comment by bwbohl** [comment]
If we are done with all the Zenodo releases?

**Comment by musicEnfanthen** [comment]
Finally closing this one. 🎉 

Thanks everyone 🙏
