### ISSUE TITLE
Verovio rendered examples missing captions

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1217]
The examples in the Guidelines rendered by Verovio are missing a `figcaption` element. It would be good to have a similar style for all example images.

**Comment by lpugin** [comment]
Sure. Could you point me to one example and explain a bit more what you expect me to do?

**Comment by rettinghaus** [comment]
Compare [cmnOctave](https://music-encoding.org/guidelines/dev/mei-all/content/cmn.html#cmnOctave) and [cmnFing](https://music-encoding.org/guidelines/dev/mei-all/content/cmn.html#cmnFing). The latter graphic carries the caption _Figure 34. Fingering in Hanon’s exercise no. 21_. Similar should be the rendered examples.

**Comment by lpugin** [comment]
I agree, it would be good. However, I am afraid I am not the right person to have this assigned to

**Comment by musicEnfanthen** [comment]
I guess this is just because the `head` element in the `cmnOctave` example (and others with `rend="verovio code"`) is empty?

https://github.com/music-encoding/music-encoding/blob/b48d5cbc4b7c232932020f456e6db3c72089782d/source/docs/04-cmn.xml#L1011-L1014

Compare to `cmnFing`:

https://github.com/music-encoding/music-encoding/blob/b48d5cbc4b7c232932020f456e6db3c72089782d/source/docs/04-cmn.xml#L1088-L1091

**Comment by musicEnfanthen** [comment]
Files are here: https://github.com/music-encoding/music-encoding/tree/develop/source/examples/verovio

**Comment by annplaksin** [comment]
Missing captions to all examples in the chapter on Mensural notation has been added in PR #1409 
Does anyone feel responsible for the other chapters?

**Comment by annplaksin** [comment]
By the way, there are also missing captions for listings. At least in the Mensural chapter, I added captions to every figure.

**Comment by musicEnfanthen** [comment]
There are something about 70 listings in metadata chapter and about 100 in cmn chapter. So I guess, applying captions to all of them is something for a very rainy day....

**Comment by krHERO** [comment]
overview of added listings

- [x] [1 Introduction to MEI](https://music-encoding.org/guidelines/dev/content/introduction.html) with #1635 
- [x] [2 Shared Concepts in MEI](https://music-encoding.org/guidelines/dev/content/shared.html) with #1635
- [x] [3 Metadata in MEI](https://music-encoding.org/guidelines/dev/content/metadata.html) with #1635
- [ ] [4 Repertoire: Common Music Notation](https://music-encoding.org/guidelines/dev/content/cmn.html)
- [x] [5 Repertoire: Mensural Notation](https://music-encoding.org/guidelines/dev/content/mensural.html) with #1409 
- [ ] [6 Repertoire: Neume Notation](https://music-encoding.org/guidelines/dev/content/neumes.html)
- [ ] [7 Repertoire: String Tablature](https://music-encoding.org/guidelines/dev/content/tablature.html)
- [ ] [8 Lyrics and Performance Directions](https://music-encoding.org/guidelines/dev/content/lyricsperfdir.html)
- [ ] [9 Text Encoding](https://music-encoding.org/guidelines/dev/content/textencoding.html)
- [ ] [10 Analysis Markup and Harmonies](https://music-encoding.org/guidelines/dev/content/analysisharm.html)
- [ ] [11 Scholarly Editing with MEI](https://music-encoding.org/guidelines/dev/content/scholarlyediting.html)
- [ ] [12 Facsimiles and Performances](https://music-encoding.org/guidelines/dev/content/facsimilesperformances.html)
- [ ] [13 Linking Data](https://music-encoding.org/guidelines/dev/content/linkingdata.html)
- [ ] [14 Integrating MEI with other Standards and Formats](https://music-encoding.org/guidelines/dev/content/integration.html)

**Comment by bwbohl** [comment]
@music-encoding/guidelines-editors We need your help in fixing this issue. Many figures in the MEI Guidelines are missing even a basic head/caption, and we would like to fix this. If you, as chapter editors, could coordinate filling those in for your chapters, that would be fantastic!

**Comment by rettinghaus** [comment]
A problem is that graphics coming from Verovio are connected to their MEI code as listing. 

<img width="963" height="902" alt="Image" src="https://github.com/user-attachments/assets/87db9bba-1f29-4200-bb1c-14669db75c8e" />

so there is no "Figure" like for all the other graphics, just the "Listing", which receives the head content.

<img width="720" height="285" alt="Image" src="https://github.com/user-attachments/assets/9900d784-dcfc-4e86-b91f-c25ba7a5923e" />
