### ISSUE TITLE
Roadmap to Release MEI v6.0

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1389]
### Before the release:

- [ ] feature freeze on GH
- [ ] Build workflow working
- [ ] release notes ready
- [ ] comparison html ready
- [ ] XSLT mei50To60 ready
- [ ] check sample-encodings
- [ ] check encoding-tools

### During the release:
  - [ ] adjust version number to `v6.0`
  - [ ] double check all meiversions in all samples
  - [ ] add tag v6.0
  - [ ] update GH action with release job
  - [ ] upgrade sample encodings
  - [ ] update examples in the guidelines
  - [ ] add corresponding tags to sample encoding repo (guidelines and schema repo do not have tags)
  - [ ] add release assets (Guidelines HTML & PDF , Schemata)
  - [ ] add release notes
  - [ ] include v6 guidelines in website menu
  - [ ] add v6 menu.html to `menus/v6/` in website repo
  - [ ] update schema & namespace section of the website
  - [ ] add comparison html to website

### After the release:
- [ ] merge release to develop
- [ ] push release assets to Zenodo
- [ ] update version number to `v6.1-dev`
- [ ] advertise release

**Comment by musicEnfanthen** [comment]
superseded by #1640
