### ISSUE TITLE
Roadmap to Release MEI v5.1

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1516]
### Before the release:

- [x] feature freeze on GH
- [x] Build workflow working
- [x] release notes ready
- [x] comparison html ready
- [x] https://github.com/music-encoding/encoding-tools/issues/42
- [x] check sample-encodings
- [x] check encoding-tools
- [x] check docker-mei (update versions of deps)
- [x] check contributors

### During the release:
  - [x] create PR from release branch to stable
  - [x] adjust version number to `v5.1` (also in [meilogo_ascii](https://github.com/music-encoding/music-encoding/blob/develop/source/assets/images/meilogo_ascii_100.txt))
  - [x] double check all meiversions in all samples
  - [x] update examples in the guidelines
  - [x] double check PDF
  - [x] double check contributors 
  - [x] merge PR from release branch to stable (triggers nothing)
  - [x] locally add tag v5.1 (with annotation: MEI 5.1) to stable
  - [x] push tag to upstream (triggers release)
  - [x] add release notes
  - [x] add release assets (PDF , Schemata)
  - [x] sign release assets: `gpg --armor --detach-sign <asset>` (see https://wiki.debian.org/Creating%20signed%20GitHub%20releases)
- #### encoding-tools
  - [x] add corresponding tags to encoding tools repo
- #### sample-encodings
  - [x] upgrade sample encodings: https://github.com/music-encoding/sample-encodings/pull/102
  - [x] add corresponding tags to sample encoding repo (guidelines and schema repo do not have tags)
- #### website
  ~~- [ ] include v6 guidelines in website menu~~
  ~~- [ ] add v6 menu.html to `menus/v6/` in website repo~~
  - [x] update schema & namespace section of the website: https://github.com/music-encoding/music-encoding.github.io/pull/731
  - [x] add comparison html to website (https://github.com/music-encoding/music-encoding.github.io/pull/732)
- #### docker-mei
  - [x] add corresponding tags to docker-mei repo

### After the release:
- [x] merge stable back to develop: https://github.com/music-encoding/music-encoding/pull/1585
- [x] update version number to `v6-dev`
   - [x] build.properties
   - [x] mei-source.xml editionStmt (responsible for version number delegated to guidelines)
   - [x] MEI.shared.xml: att.meiVersion
   - [ ] customizations
   - [x] examples
- [x] push release assets to Zenodo (https://zenodo.org/communities/mei)
- [x] advertise release (https://github.com/music-encoding/music-encoding.github.io/pull/733)

Finally:
- [x]  delete release branches in all repos

**Comment by musicEnfanthen** [comment]
Mission completed 🎉
