### ISSUE TITLE
Roadmap to PDF Guidelines

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#959]
Steps needed:

XSLTs
- [x] prepare XSLTs to handle PDF Guideline creation
- [x] integrate XSLTs into build workflow
- [x]  adjust to different build environments
- [x] merge pdf-guidelines branch to dev

DOCKER
- [x] prepare docker build workflows for the following steps:
    - [x] render live MEI examples to SVG (https://github.com/Edirom/staticVerovioConverter)
    - [x] generate complete PDF with [princexml](https://www.princexml.com/)
    - [x] integrate everything in docker-mei container [https://github.com/music-encoding/docker-mei](https://github.com/music-encoding/docker-mei)

- [x] documentation of build workflow with docker (README)

GH ACTIONS
- [x] include docker workflows in [deploy action](https://github.com/music-encoding/music-encoding/blob/develop/.github/workflows/deploy.yml)
  - [x] [build with ANT]
  - [x] check path structure of local and CI builds (#960)
  - [x] render live MEI examples to SVG 
  - [x] generate PDF  

The build process should be the same for dev build and tagged releases and work with both. Additional features for a release should be

- [ ] automatically creating a release on GitHub
- [ ] automatically adding release assets (Guidelines HTML & PDF , Schemata)

POTENTIAL ANT IMPROVEMENTS

- [ ] https://github.com/music-encoding/music-encoding/compare/pdf-guidelines-test...improve-gh-param-handling?expand=1
- [x] https://github.com/TEIC/Stylesheets/issues/544
- [ ] https://github.com/bwbohl/music-encoding/tree/feature-build-on-pr
- [ ] https://github.com/bwbohl/music-encoding/tree/feature_cleanBeforBuild

POTENTIAL STYLING IMPROVEMENTS

- [ ] https://github.com/bwbohl/music-encoding/tree/fix/classHeadingPadding

POTENTIAL OTHER IMPROVEMENTS

- [ ] https://github.com/music-encoding/music-encoding/pull/806

ALSO CHECK:

- [ ] #834

**Comment by lpugin** [comment]
@kepper don't you want to have the script for converting the MEI within this repository? I am sure that https://github.com/Edirom/staticVerovioConverter works but then things (e.g., options for the conversions) are spread over different repository. It seems to me that a Python script call from the GH action would do the job - we use that a lot.

**Comment by kepper** [comment]
I'm happy to do whatever is necessary – and this was the easist thing to set up with the skills I have. Not saying this is particularly good or efficient, but it does work quite well. However, in the long run we hope to get all the different build steps into one single docker image (right now, it's a pipe of Ant doing the XSLT plus some more, then the staticVerovioConverter Docker image to render some MEI files to SVG, and then another Docker image with the PrinceXML conversion. Ideally, we can wrap this up in one single image that does the whole transformation, and the GitHub Action calling this would then take the generated assets and push them to the /guidelines and /schema repo. The hope would be to simplify local building – in essence, you would need to call one `docker run` locally, and wouldn't have to worry about installing all the different dependencies. As soon as we get to these optimizations, I can easily see how to switch to your proposed Python script. For now, I'm inclined to stick with what we have and make sure we get the whole workflow running first. Ok?

**Comment by lpugin** [comment]
OK, thanks for the explanation. Sounds fine. I guess if everything runs from a single docker image then having a Python script vs a JavaScript script makes no real difference. My concern is mostly about having multiple repos / docker images and configurations spread in different places. It seems it will not be the case in the end. Please let me know if you think I can help.

**Comment by kepper** [comment]
Oh, you can certainly help ;-) At this point, we really don't need the Git Repo at https://github.com/Edirom/staticVerovioConverter, but only the Docker image generated from it, available from https://hub.docker.com/r/edirom/staticverovioconverter. In the process, we just run that image, passing in a folder with files to be converted. So for our current GitHub Actions, it is just one call: `docker run --rm -v $(pwd):/data edirom/staticverovioconverter:latest`. Sure we can replace this single step with something more efficient or elegant, but that is an optimization we can implemented after this is working at all…

**Comment by kepper** [comment]
Just for documentation purposes, the other Docker image we need to run (which basically ticks the _generate complete PDF with princexml_ box above, we just need some more integration testing…) is `docker run --rm -it -v $(pwd):/out yeslogic/prince:14.2 /out/source/MEI_Guidelines.html -o /out/exampleGuidelines.pdf --log /out/princeLog.txt -v`

**Comment by bwbohl** [comment]
I created a new branch [rebase](https://github.com/bwbohl/music-encoding/tree/rebase) in my fork that was a rebase of [pdf-guidelines-test](https://github.com/music-encoding/music-encoding/tree/pdf-guidelines-test) on [develop](https://github.com/music-encoding/music-encoding/tree/develop). Afterwards, I merged and implemented some build fixes (e.g. #993) and added some improvements (e.g.  #996) and kept the branch in sync with new modifications of the main-repo develop branch.

A careful diff should still be made against the develop branch before merging but the only thing that made me stumble was the diff of `source/css/*` and `source/assets/css/*`.

For testing the build process locally, I wrote some bash scripts:

- build.sh ( a wrapper file executing the following other shell scripts, which are there for debugging the single steps)
  - build_ant.sh (calling reset and then docker bwbohl/docker-mei container to build all that can be done so far via ant)
  - build_generate-images.sh (calling docker edirom/staticveroviocontainer to convert mei files to svg and copy them to dist folder)
  - build_prince.sh (calling docker container that converts Guidelines HTML in build folder to PDF in dist/guidelines/dev)
- entrypoint_ant-worker.sh (entrypoint file for calling bwbohl/docker-mei container)


As a result, I can tell that it works great except for:

GH action
- [ ] if the prince docker will be started from  the GHAction question is: how will it know the exact name of the generated `MEI_Guidelines*.html` file being something like `MEI_Guidelines_v5.0.0-dev.html` and use the basename for the generated PDF? Something I tackled in the bash scripts but that should be solved differently in the GHAction context

local
- [x] docker run of yeslogic/prince:14.2 might require you add a `--platform=linux/amd64` in order to run it on machines with other architecture
- [ ] Warnings from the individual components in build log (search for warning in terminal or logfiles)
  - [x] verovio warnings
  - [ ] prince warnings
    - [ ] prince: /out/build/assets/css/print/tei.css: warning: unsupported properties: text-decoration-line, text-decoration-style
    - [x] prince: /out/build/assets/images/modules/edittrans/schütz_sopranoclef.png: warning: can't open input file: No such file or directory
    - [ ] prince: /out/build/assets/images/ORCID_iD.svg: warning: unsupported properties: enable-background
    - [x] prince: page 45: warning: no font for Private Use Area character U+E1D3, fallback to U+2BD1 ⯑
    - [x] prince: page 341: warning: no font for Combining Diacritical Marks for Symbols character U+20E5, fallback to U+2BD1 ⯑ 

CSS
- [ ] Some styling issues in the resulting PDF (just a quick scoll-through)
  - [x] Title placement on title page 
  - [ ] blue line above and below listings intended?
  - [ ]  some odd image placement in 6.4 Samples of MEI encodings
  - [ ]  some text running beyond page end in Element Specifications, e.g. `<repository>`
  - [ ] some orphans or widows in code examples

**Comment by bwbohl** [comment]
The Docker image at https://github.com/music-encoding/docker-mei now can handle all aspects of building both schema (rng, compiled odd) and guidelines (HTML, PDF), and it is automatically cross-compiled for amd64 and arm64.
Nevertheless, there still are some questions concerning e.g. location of certain scripts (music-encoding vs. docker repo) or granularity of the build for offline building, building without docker, and of course documentation is still to be done.

**Comment by ahankinson** [comment]
@bwbohl I think this can be closed? Maybe the improvements can go in separate issues(s) since the "big task" for this issue has been completed?

**Comment by musicEnfanthen** [comment]
@ahankinson Yes, you are right. Moving the further development to #1162 and closing this one.
